{% set url_name = "python-spake2" %}
{% set name = "spake2" %}
{% set version = "0.8" %}
{% set sha256 = "c96c1d9438ca7f738959690b0860473b5bf8f8b95884f78fd5af11d2e6db662f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ url_name }}-{{ version }}.tar.gz
  url: https://github.com/warner/{{ url_name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 4
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip 
  run:
    - python >={{ python_min }}
    - hkdf

test:
  requires:
    - python {{ python_min }}
  imports:
    - spake2

about:
  home: https://github.com/warner/python-spake2
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'This library implements the SPAKE2 password-authenticated key exchange ("PAKE") algorithm. '

  description: |
    This library implements the SPAKE2 password-authenticated key exchange ("PAKE") algorithm. This allows two parties, who share a weak password, to safely derive a strong shared secret (and therefore build an encrypted+authenticated channel). A passive attacker who eavesdrops on the connection learns no information about the password or the generated secret. An active attacker (man-in-the-middle) gets exactly one guess at the password, and unless they get it right, they learn no information about the password or the generated secret. Each execution of the protocol enables one guess. The use of a weak password is made safer by the rate-limiting of guesses: no off-line dictionary attack is available to the network-level attacker, and the protocol does not depend upon having previously-established confidentiality of the network (unlike e.g. sending a plaintext password over TLS). The protocol requires the exchange of one pair of messages, so only one round trip is necessary to establish the session key. If key-confirmation is necessary, that will require a second round trip. All messages are bytestrings. For the default security level (using the Ed25519 elliptic curve, roughly equivalent to an 128-bit symmetric key), the message is 33 bytes long.
  doc_url: https://github.com/warner/python-spake2
  dev_url: https://github.com/warner/python-spake2

extra:
  recipe-maintainers:
    - CJ-Wright
