# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "vjBoRPIPCAX5/ld4EoWDNQBDaSnm/5kjqPzMZ4sy/8vglygZgbHd1Dq7A8k3JrU1sru1q4UiVIqPu1mgURnkDUcLbCsq0KehJpPbYTwibxlW+GMcZofEQ5H/hl/GRUpIcXCo0VO6oEYCENDslu7SK/4mLw2UCkWM/u5mc+y4QNRlrMNkY7sgUsnxayFlFKO06NX2ONij9A0iSERYJcoyI86B24Fqein+Lz6Z/0CoyQs0VaEZ6YAEi4PxQFrqE3Nsh3cpoHczmIj0Wtp9HAbB71h4LnEv5zPpa5F/6m23/6M4zQFClxD6Yd3cLlfDb6S0A2elit3niqW2IM9piXW64EdxEFVNWxzjlE8nDBgND+QFto/pMdJKXxw+oe6G7NfHpv+l6TSuCGkmnLRO7X4VPtJjcT9nnRXuKmLGrRs6rNuJMLmuUtVl8Nxh9+5M+kkRsEh/iEZvMBGWB/BQ0V1koTfkZN4Xgbc/sTSEQKBlY2wTvdYEJVpaMet0PJKh3gjKdRJ33Gd9F9pIXmJ/jeOZB/dkdzHcXrpar2jbHNTqm8Pm7hRA/2lmG8DRO4MAxKs2nsiOoatF2pHY5P4n2xtNORPipeymSSi1MW+nWhcL/rApgLxZnEE4GKmrASX1MznmwzG9GAZUKQ1lSP/wyeBD2PRZBS1U01/0cyTP7KIBBVo="


before_install:
    # Remove homebrew.
    - brew remove --force --ignore-dependencies $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
