travis:
  secure:
    BINSTAR_TOKEN: EaRlMEiWRdOArz8ryUWMhqyVDnrbKE1hPsHiAaDyMYH5ykaLZc07L4uRv1qWmir9kHaBU2nw2j6JjE9TuNrt9khtBy+pblNuhS/VrscWVhlafa55MhHA+T4IEjX3cn993qt5avPfJsdccBNSxkDEVqBKufNtBFaYrc0H7bRX5kwwArvx0gcUzP8wjdcHkogb3boHfjhjilI+FncvaeimHzB6W1dARbHv1ZL4LAgG//AbRjcU7cwln/ej/C0ME4E8E0wePKBXhMlZ08kZCA4lYHMbc9cE7GrWm8EKvR7oBK9uFr+Ujd19rH30Ti4BLGtV4gnFhxaom/mnKY6ppLQfH6EjeaW+KaTYYbMbnCUkORh7/ar4m0+bygh8pQl6DW9vqJpPqCxHr6HmJFH2DYuiuXFYchYBz6h2QamIDrcg5bpjqN9Qv/2WFkCNaVaNcKBSWmHrMnPXXzMPYLTqOaMc039dX/sgLGVH3oqAlscclUew5V8+mdpIacDGeV7zhasHa20uCLjbwkC6bMFoT1C+J+uyqtI94UQqRbvGV+cKFQ5R4iwhZ6gZABP5B2M2ZYilg8jkvNRBQvDSNlUa7ITomKfzdg8Wu1K8Je2l8JeK7Vf1nwpsOnR004JzA7dBDbD3zPWpZ+N/ELVTMOl8Z8M6J1xl78+piOs4WwJLkD5K6uo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
