travis:
  secure:
    BINSTAR_TOKEN: vjBoRPIPCAX5/ld4EoWDNQBDaSnm/5kjqPzMZ4sy/8vglygZgbHd1Dq7A8k3JrU1sru1q4UiVIqPu1mgURnkDUcLbCsq0KehJpPbYTwibxlW+GMcZofEQ5H/hl/GRUpIcXCo0VO6oEYCENDslu7SK/4mLw2UCkWM/u5mc+y4QNRlrMNkY7sgUsnxayFlFKO06NX2ONij9A0iSERYJcoyI86B24Fqein+Lz6Z/0CoyQs0VaEZ6YAEi4PxQFrqE3Nsh3cpoHczmIj0Wtp9HAbB71h4LnEv5zPpa5F/6m23/6M4zQFClxD6Yd3cLlfDb6S0A2elit3niqW2IM9piXW64EdxEFVNWxzjlE8nDBgND+QFto/pMdJKXxw+oe6G7NfHpv+l6TSuCGkmnLRO7X4VPtJjcT9nnRXuKmLGrRs6rNuJMLmuUtVl8Nxh9+5M+kkRsEh/iEZvMBGWB/BQ0V1koTfkZN4Xgbc/sTSEQKBlY2wTvdYEJVpaMet0PJKh3gjKdRJ33Gd9F9pIXmJ/jeOZB/dkdzHcXrpar2jbHNTqm8Pm7hRA/2lmG8DRO4MAxKs2nsiOoatF2pHY5P4n2xtNORPipeymSSi1MW+nWhcL/rApgLxZnEE4GKmrASX1MznmwzG9GAZUKQ1lSP/wyeBD2PRZBS1U01/0cyTP7KIBBVo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
